"""empty message

Revision ID: bb0f98d5b1f5
Revises: d0647e577df5
Create Date: 2023-02-09 18:47:29.871241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0f98d5b1f5'
down_revision = 'd0647e577df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_capthca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_capthca', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###
