"""empty message

Revision ID: d0647e577df5
Revises: 851683b28dcc
Create Date: 2023-02-08 19:41:01.558515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0647e577df5'
down_revision = '851683b28dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_capthca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha', sa.String(length=100), nullable=False))
        batch_op.drop_column('capthca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_capthca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capthca', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('captcha')

    # ### end Alembic commands ###
